# Generated by Django 4.2.4 on 2023-09-23 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsystem', '0023_alter_python_syllabus_subject_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='python_syllabus',
            name='subject_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schoolsystem.subject'),
        ),
    ]
