# Generated by Django 4.2.4 on 2023-09-25 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsystem', '0024_alter_python_syllabus_subject_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('topics', models.TextField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolsystem.subject')),
            ],
        ),
        migrations.DeleteModel(
            name='Python_Syllabus',
        ),
    ]
