# Generated by Django 4.2.4 on 2023-09-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsystem', '0025_syllabus_delete_python_syllabus'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='video_link',
            field=models.URLField(null=True),
        ),
    ]
