# Generated by Django 4.2.4 on 2023-09-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsystem', '0026_syllabus_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='week',
            field=models.TextField(),
        ),
    ]
