# Generated by Django 4.2.4 on 2023-09-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsystem', '0027_alter_syllabus_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='notes_pdf',
            field=models.FileField(null=True, upload_to='media/notes_pdf'),
        ),
    ]
