# Generated by Django 4.2.4 on 2023-09-30 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsystem', '0029_diary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diary_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolsystem.diary')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schoolsystem.student')),
            ],
        ),
    ]
