# Generated by Django 4.2.4 on 2023-09-30 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsystem', '0030_daily_diary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Daily_Diary',
        ),
    ]
