# Generated by Django 4.2.4 on 2023-10-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsystem', '0031_delete_daily_diary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='notes_pdf',
            field=models.FileField(blank=True, null=True, upload_to='media/notes_pdf'),
        ),
    ]
