# Generated by Django 4.2.4 on 2023-10-07 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsystem', '0032_alter_syllabus_notes_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_date', models.DateField()),
                ('assign_time', models.TimeField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolsystem.staff')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolsystem.subject')),
            ],
        ),
    ]
