# Generated by Django 4.2.4 on 2023-10-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsystem', '0033_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(null=True),
        ),
    ]
