# Generated by Django 4.2.4 on 2023-10-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsystem', '0035_staff_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='room_no',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
