# Generated by Django 4.2.4 on 2023-10-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsystem', '0036_schedule_room_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=255)),
                ('exam_subject', models.CharField(max_length=255)),
                ('exam_class', models.CharField(max_length=255)),
                ('exam_teacher', models.CharField(max_length=255)),
                ('exam_time', models.DateTimeField()),
                ('exam_question', models.TextField()),
                ('pdf_content', models.BinaryField()),
            ],
        ),
    ]
