# Generated by Django 4.2.4 on 2023-10-24 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsystem', '0038_exampaper_exam_time_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampaper',
            name='exam_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolsystem.subject'),
        ),
    ]
