# Generated by Django 4.2.4 on 2023-10-24 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsystem', '0039_alter_exampaper_exam_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampaper',
            name='exam_subject',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolsystem.subject'),
        ),
    ]
