# Generated by Django 4.2.4 on 2023-11-09 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsystem', '0041_noticeboard_students_noticeboard_teachers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('any_query', models.TextField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolsystem.student')),
            ],
        ),
    ]
