# Generated by Django 4.2.4 on 2023-11-25 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsystem', '0042_student_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Support_Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_reply', models.TextField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolsystem.student_support')),
            ],
        ),
    ]
