# Generated by Django 4.2.4 on 2023-12-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsystem', '0044_alter_student_support_reply_subject_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='serial_number',
            field=models.CharField(default='#0000', max_length=20, unique=True),
        ),
    ]
